package com.udacity.jwdnd.c1.review.mapper;

import com.udacity.jwdnd.c1.review.model.User;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Select;

@Mapper
public interface UserMapper {

    @Select("SELECT * FROM Users WHERE username = #{username}")
    User getUser(String username);

    @Insert("INSERT INTO Users(username, salt, password, firstname, lastname)" +
            "VALUES(#{username}, #{salt}, #{password}, #{firstName}, #{lastName})") // calls getUsername(), getFirstName(), ...
    @Options(useGeneratedKeys = true, keyProperty = "userid")
        // normally, returns number of affected rows, 0 for create,
        // but with above option it returns the key (here userid) generated by the insertion
    int saveUser(User user);
}
